# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b1bcb1f406f72c1a8f6117c9c5a0681a896a6937d20837483490186ab7eff8bbbcfd31476270cff0a0413036aabe5388996a7bdbf5b9942e1dfb6a53305c40b

test:
  secret_key_base: 0b754818598ddeae317df958c3b19f18b0984eeb61299642dac33a8fec50cd52b7fd67be26c0d81fa7c93c150cd7665997ed2e85536b760e230f40b2629f752a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
